FROM python:3.11-slim

RUN pip install --upgrade pip

WORKDIR /app

COPY ./producer /app
COPY ../requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

CMD [ "python",  "-u", "./app_producer.py" ]
